Import Libraries

In [1]:
pip install numpy pandas matplotlib seaborn scikit-learn scipy catboost xgboost lightgbm optuna joblib jupyter notebook ipykernel kaggle kagglehub plotly missingno tqdm

Collecting numpy
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Collecting matplotlib
  Using cached matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Collecting scipy
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Collecting catboost
  Using cached catboost-1.2.10-cp310-cp310-win_amd64.whl (100.2 MB)
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Collecting lightgbm
  Using cached lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
Collecting optuna
  Using cached optuna-4.9.0-py3-none-any.whl (425 kB)
Collecting joblib
  Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Collecting notebook
  Using cached notebook-7.6.1-py3-none-any.whl (5.5 MB)
Requirement already satisfied: ipykernel in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (7.3.0)
Collecting kaggle
  Using cached kaggle-1.7.4.5-py3-none-any.whl (181 kB)
Collecting kagglehub
  Using cached kagglehub-1.0.2-py3-none-any.whl (70 kB)
Collecting plotly
  Using cached plotly-6.9.0-py3-none-any.whl (9.9 MB)
Collecting missingno
  Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Collecting tqdm
  Using cached tqdm-4.69.1-py3-none-any.whl (675 kB)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     -------------------------------------- 508.3/508.3 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Collecting pyparsing>=3
  Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Requirement already satisfied: packaging>=20.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=8
  Using cached pillow-12.3.0-cp310-cp310-win_amd64.whl (7.2 MB)
Collecting kiwisolver>=1.3.1
  Using cached kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.63.0-cp310-cp310-win_amd64.whl (1.6 MB)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting graphviz
  Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Requirement already satisfied: six in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from catboost) (1.17.0)
Collecting narwhals>=1.15
  Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Collecting PyYAML
  Using cached pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
Collecting alembic>=1.5.0
  Using cached alembic-1.18.5-py3-none-any.whl (264 kB)
Collecting sqlalchemy>=1.4.2
  Using cached sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting colorlog
  Using cached colorlog-6.12.0-py3-none-any.whl (12 kB)
Collecting jupyterlab
  Using cached jupyterlab-4.6.2-py3-none-any.whl (17.2 MB)
Collecting jupyter-console
  Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Collecting ipywidgets
  Using cached ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Collecting nbconvert
  Using cached nbconvert-7.17.1-py3-none-any.whl (261 kB)
Collecting jupyterlab-server<3,>=2.28.0
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl (59 kB)
Collecting jupyter-server<3,>=2.19.0
  Using cached jupyter_server-2.20.0-py3-none-any.whl (393 kB)
Requirement already satisfied: tornado>=6.2.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from notebook) (6.5.7)
Collecting jupyter-builder<2,>=1.0.2
  Using cached jupyter_builder-1.1.1-py3-none-any.whl (913 kB)
Collecting notebook-shim<0.3,>=0.2
  Using cached notebook_shim-0.2.4-py3-none-any.whl (13 kB)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: comm>=0.1.1 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: pyzmq>=25 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: nest-asyncio2>=1.7.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (1.7.2)
Requirement already satisfied: psutil>=5.7 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (1.8.21)
Requirement already satisfied: jupyter-client>=8.9.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (8.9.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (5.15.1)
Requirement already satisfied: ipython>=7.23.1 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipykernel) (8.39.0)
Collecting protobuf
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting certifi>=14.05.14
  Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Collecting idna
  Using cached idna-3.18-py3-none-any.whl (65 kB)
Collecting charset-normalizer
  Using cached charset_normalizer-3.4.9-cp310-cp310-win_amd64.whl (162 kB)
Collecting bleach
  Using cached bleach-6.4.0-py3-none-any.whl (165 kB)
Collecting python-slugify
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Collecting text-unidecode
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting urllib3>=1.15.1
  Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Requirement already satisfied: setuptools>=21.0.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from kaggle) (63.2.0)
Collecting kagglesdk<1.0,>=0.1.22
  Using cached kagglesdk-0.1.28-py3-none-any.whl (230 kB)
Requirement already satisfied: colorama in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from tqdm) (0.4.6)
Collecting tomli
  Using cached tomli-2.4.1-py3-none-any.whl (14 kB)
Requirement already satisfied: typing-extensions>=4.12 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Collecting Mako
  Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Requirement already satisfied: decorator in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.3.1)
Requirement already satisfied: pygments>=2.4.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: jedi>=0.16 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: exceptiongroup in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.3.1)
Requirement already satisfied: stack_data in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.11.0)
Collecting prometheus-client>=0.9
  Using cached prometheus_client-0.26.0-py3-none-any.whl (64 kB)
Collecting nbformat>=5.3.0
  Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Collecting jinja2>=3.0.3
  Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Collecting overrides>=5.0
  Using cached overrides-7.7.0-py3-none-any.whl (17 kB)
Collecting pywinpty!=3.0.4,>=2.0.1
  Using cached pywinpty-3.0.5-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting argon2-cffi>=21.1
  Using cached argon2_cffi-25.1.0-py3-none-any.whl (14 kB)
Collecting websocket-client>=1.7
  Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Collecting jupyter-server-terminals>=0.4.4
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl (13 kB)
Collecting anyio>=3.1.0
  Using cached anyio-4.14.2-py3-none-any.whl (125 kB)
Collecting jupyter-events>=0.11.0
  Using cached jupyter_events-0.12.1-py3-none-any.whl (19 kB)
Collecting send2trash>=1.8.2
  Using cached send2trash-2.1.0-py3-none-any.whl (17 kB)
Collecting terminado>=0.8.3
  Using cached terminado-0.18.1-py3-none-any.whl (14 kB)
Collecting async-lru>=1.0.0
  Using cached async_lru-2.3.0-py3-none-any.whl (8.4 kB)
Collecting jupyter-lsp>=2.0.0
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl (77 kB)
Collecting httpx<1,>=0.25.0
  Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Collecting json5>=0.9.0
  Using cached json5-0.15.0-py3-none-any.whl (36 kB)
Collecting babel>=2.10
  Using cached babel-2.18.0-py3-none-any.whl (10.2 MB)
Collecting jsonschema>=4.18.0
  Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting mistune<4,>=2.0.3
  Using cached mistune-3.3.4-py3-none-any.whl (66 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting nbclient>=0.5.0
  Using cached nbclient-0.11.0-py3-none-any.whl (25 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting markupsafe>=2.0
  Using cached markupsafe-3.0.3-cp310-cp310-win_amd64.whl (15 kB)
Collecting greenlet>=1
  Using cached greenlet-3.5.4-cp310-cp310-win_amd64.whl (246 kB)
Collecting widgetsnbextension~=4.0.14
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
Collecting jupyterlab_widgets~=3.0.15
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl (31 kB)
Collecting tinycss2>=1.1.0
  Using cached tinycss2-1.5.1-py3-none-any.whl (28 kB)
Collecting httpcore==1.*
  Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Collecting h11>=0.16
  Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.7)
Collecting referencing>=0.28.4
  Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Collecting rpds-py>=0.25.0
  Using cached rpds_py-0.30.0-cp310-cp310-win_amd64.whl (235 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting rfc3339-validator
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Collecting rfc3986-validator>=0.1.1
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Collecting python-json-logger>=2.0.4
  Using cached python_json_logger-4.1.0-py3-none-any.whl (15 kB)
Collecting fastjsonschema>=2.15
  Downloading fastjsonschema-2.22.0-py3-none-any.whl (26 kB)
Requirement already satisfied: wcwidth in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.8.2)
Collecting soupsieve>=1.6.1
  Using cached soupsieve-2.9.1-py3-none-any.whl (37 kB)
Requirement already satisfied: pure-eval in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Requirement already satisfied: executing>=1.2.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\predicting student health risk\student-health-risk\.venv\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.2)
Collecting isoduration
  Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
Collecting rfc3987-syntax>=1.1.0
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl (8.0 kB)
Collecting webcolors>=24.6.0
  Using cached webcolors-25.10.0-py3-none-any.whl (14 kB)
Collecting jsonpointer>1.13
  Using cached jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Collecting fqdn
  Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Collecting uri-template
  Using cached uri_template-1.3.0-py3-none-any.whl (11 kB)
Collecting cffi>=1.0.1
  Using cached cffi-2.1.0-cp310-cp310-win_amd64.whl (185 kB)
Collecting pycparser
  Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Collecting lark>=1.2.2
  Using cached lark-1.3.1-py3-none-any.whl (113 kB)
Collecting arrow>=0.15.0
  Using cached arrow-1.4.0-py3-none-any.whl (68 kB)
Installing collected packages: webencodings, text-unidecode, pytz, fastjsonschema, widgetsnbextension, websocket-client, webcolors, urllib3, uri-template, tzdata, tqdm, tomli, tinycss2, threadpoolctl, soupsieve, send2trash, rpds-py, rfc3986-validator, rfc3339-validator, PyYAML, pywinpty, python-slugify, python-json-logger, pyparsing, pycparser, protobuf, prometheus-client, pillow, pandocfilters, overrides, numpy, narwhals, mistune, markupsafe, lark, kiwisolver, jupyterlab_widgets, jupyterlab-pygments, jsonpointer, json5, joblib, idna, h11, greenlet, graphviz, fqdn, fonttools, defusedxml, cycler, colorlog, charset-normalizer, certifi, bleach, babel, attrs, async-lru, terminado, sqlalchemy, scipy, rfc3987-syntax, requests, referencing, plotly, pandas, Mako, jupyter-builder, jinja2, httpcore, contourpy, cffi, beautifulsoup4, arrow, anyio, xgboost, scikit-learn, matplotlib, lightgbm, kagglesdk, kaggle, jupyter-server-terminals, jsonschema-specifications, isoduration, ipywidgets, httpx, argon2-cffi-bindings, alembic, seaborn, optuna, kagglehub, jupyter-console, jsonschema, catboost, argon2-cffi, nbformat, missingno, nbclient, jupyter-events, nbconvert, jupyter-server, notebook-shim, jupyterlab-server, jupyter-lsp, jupyterlab, notebook, jupyter
Successfully installed Mako-1.3.12 PyYAML-6.0.3 alembic-1.18.5 anyio-4.14.2 argon2-cffi-25.1.0 argon2-cffi-bindings-25.1.0 arrow-1.4.0 async-lru-2.3.0 attrs-26.1.0 babel-2.18.0 beautifulsoup4-4.15.0 bleach-6.4.0 catboost-1.2.10 certifi-2026.7.22 cffi-2.1.0 charset-normalizer-3.4.9 colorlog-6.12.0 contourpy-1.3.2 cycler-0.12.1 defusedxml-0.7.1 fastjsonschema-2.22.0 fonttools-4.63.0 fqdn-1.5.1 graphviz-0.21 greenlet-3.5.4 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.18 ipywidgets-8.1.8 isoduration-20.11.0 jinja2-3.1.6 joblib-1.5.3 json5-0.15.0 jsonpointer-3.1.1 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 jupyter-1.1.1 jupyter-builder-1.1.1 jupyter-console-6.6.3 jupyter-events-0.12.1 jupyter-lsp-2.3.1 jupyter-server-2.20.0 jupyter-server-terminals-0.5.4 jupyterlab-4.6.2 jupyterlab-pygments-0.3.0 jupyterlab-server-2.28.0 jupyterlab_widgets-3.0.16 kaggle-1.7.4.5 kagglehub-1.0.2 kagglesdk-0.1.28 kiwisolver-1.5.0 lark-1.3.1 lightgbm-4.7.0 markupsafe-3.0.3 matplotlib-3.10.9 missingno-0.5.2 mistune-3.3.4 narwhals-2.24.0 nbclient-0.11.0 nbconvert-7.17.1 nbformat-5.10.4 notebook-7.6.1 notebook-shim-0.2.4 numpy-2.2.6 optuna-4.9.0 overrides-7.7.0 pandas-2.3.3 pandocfilters-1.5.1 pillow-12.3.0 plotly-6.9.0 prometheus-client-0.26.0 protobuf-7.35.1 pycparser-3.0 pyparsing-3.3.2 python-json-logger-4.1.0 python-slugify-8.0.4 pytz-2026.3.post1 pywinpty-3.0.5 referencing-0.37.0 requests-2.34.2 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 rfc3987-syntax-1.1.0 rpds-py-0.30.0 scikit-learn-1.7.2 scipy-1.15.3 seaborn-0.13.2 send2trash-2.1.0 soupsieve-2.9.1 sqlalchemy-2.0.51 terminado-0.18.1 text-unidecode-1.3 threadpoolctl-3.6.0 tinycss2-1.5.1 tomli-2.4.1 tqdm-4.69.1 tzdata-2026.3 uri-template-1.3.0 urllib3-2.7.0 webcolors-25.10.0 webencodings-0.5.1 websocket-client-1.9.0 widgetsnbextension-4.0.15 xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import warnings
warnings.filterwarnings("ignore")

import sys
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

# Add project root to Python path
PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [4]:
from src.preprocessing import fill_categorical_missing
from src.feature_engineering import create_features
from src.evaluation import evaluate_model

In [5]:
train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")

print(train.shape)
print(test.shape)

(690088, 15)
(295753, 14)

In [6]:
train = create_features(train)
test = create_features(test)

print(train.shape)
print(test.shape)

(690088, 20)
(295753, 19)

In [7]:
new_features = [
    "activity_score",
    "calories_per_step",
    "water_per_exercise",
    "exercise_sleep_ratio",
    "bmi_category"
]

train[new_features].head()

,activity_score,calories_per_step,water_per_exercise,exercise_sleep_ratio,bmi_category
0,26254.8,1.638282,0.089423,3.183280,overweight
1,493560.9,0.198746,0.024754,7.641654,overweight
2,541629.6,0.189069,0.040921,6.057234,normal
3,429722.6,0.366551,0.033169,10.508772,normal
4,302864.0,0.388762,0.047872,5.589307,overweight

In [8]:
X = train.drop(columns=["health_condition"])
y = train["health_condition"]

X_test = test.copy()

In [9]:
X = fill_categorical_missing(X)
X_test = fill_categorical_missing(X_test)

In [10]:
cat_features = X.select_dtypes(include="object").columns.tolist()

print(cat_features)

['diet_type', 'stress_level', 'sleep_quality', 'physical_activity_level', 'smoking_alcohol', 'gender', 'bmi_category']

In [11]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [13]:
model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="MultiClass",
    eval_metric="Accuracy",
    random_seed=42,
    verbose=100
)
model

CatBoostClassifier(depth=8, eval_metric='Accuracy', iterations=1000, learning_rate=0.05, loss_function='MultiClass', random_seed=42, verbose=100)

In [14]:
model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_valid, y_valid),
    use_best_model=True
)

0:	learn: 0.9402866	test: 0.9425147	best: 0.9425147 (0)	total: 1.01s	remaining: 16m 51s
100:	learn: 0.9658485	test: 0.9661711	best: 0.9661711 (99)	total: 1m 22s	remaining: 12m 13s
200:	learn: 0.9664590	test: 0.9664174	best: 0.9664174 (200)	total: 2m 58s	remaining: 11m 48s
300:	learn: 0.9670259	test: 0.9665261	best: 0.9665551 (246)	total: 4m 37s	remaining: 10m 44s
400:	learn: 0.9677722	test: 0.9665478	best: 0.9666058 (385)	total: 6m 16s	remaining: 9m 21s
500:	learn: 0.9683319	test: 0.9666565	best: 0.9666855 (452)	total: 7m 50s	remaining: 7m 48s
600:	learn: 0.9689822	test: 0.9667507	best: 0.9668014 (596)	total: 9m 24s	remaining: 6m 15s
700:	learn: 0.9694966	test: 0.9668666	best: 0.9668956 (686)	total: 11m 2s	remaining: 4m 42s
800:	learn: 0.9700346	test: 0.9669101	best: 0.9669101 (789)	total: 12m 40s	remaining: 3m 8s
900:	learn: 0.9705689	test: 0.9668666	best: 0.9669826 (831)	total: 14m 14s	remaining: 1m 33s
999:	learn: 0.9710562	test: 0.9669971	best: 0.9669971 (999)	total: 15m 47s	remaining: 0us

bestTest = 0.9669970584
bestIteration = 999

CatBoostClassifier(depth=8, eval_metric='Accuracy', iterations=1000, learning_rate=0.05, loss_function='MultiClass', random_seed=42, verbose=100)

Evaluate

In [15]:
pred = model.predict(X_valid)

evaluate_model(y_valid, pred)

==================================================
Balanced Accuracy
==================================================
0.8738720050994512

==================================================
Classification Report
==================================================
              precision    recall  f1-score   support

     at-risk       0.97      0.99      0.98    118512
         fit       0.94      0.83      0.88      7961
   unhealthy       0.95      0.80      0.87     11545

    accuracy                           0.97    138018
   macro avg       0.95      0.87      0.91    138018
weighted avg       0.97      0.97      0.97    138018

==================================================
Confusion Matrix
==================================================
[[117611    423    478]
 [  1362   6569     30]
 [  2247     15   9283]]

Feature Importance

In [16]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

importance.head(20)

                    Feature  Importance
1            sleep_duration   27.925308
9              stress_level   25.674990
11  physical_activity_level   10.727754
3                       bmi    8.314283
2                heart_rate    2.754001
7              water_intake    2.680963
14           activity_score    2.561779
0                        id    2.478773
17     exercise_sleep_ratio    2.214662
4       calorie_expenditure    2.104915
12          smoking_alcohol    2.100677
10            sleep_quality    1.817372
5                step_count    1.778845
6         exercise_duration    1.691175
16       water_per_exercise    1.519059
15        calories_per_step    1.510116
18             bmi_category    0.889237
13                   gender    0.803572
8                 diet_type    0.452519