In [27]:
# ==========================================
# Student Health Risk Prediction
# CatBoost + Optuna (GPU)
# Kaggle Competition Notebook
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import json
import os
import sys
import random

import numpy as np
import pandas as pd

from catboost import CatBoostClassifier

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score

import optuna
sys.path.append(os.path.abspath(".."))
from src.preprocessing import preprocess
from src.feature_engineering import create_features

In [22]:
# ==========================================
# Configuration
# ==========================================

RANDOM_STATE = 42

TARGET = "health_condition"

TRAIN_PATH = "../data/train.csv"
TEST_PATH = "../data/test.csv"

MODEL_DIR = "models"

os.makedirs(MODEL_DIR, exist_ok=True)

np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

In [23]:
# ==========================================
# Load Dataset
# ==========================================

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)

print("Train Shape :", train.shape)
print("Test Shape  :", test.shape)

train.head()

Train Shape : (690088, 15)
Test Shape  : (295753, 14)

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male

In [24]:
# ==========================================
# Save IDs
# ==========================================

train_ids = train["id"].copy()

test_ids = test["id"].copy()

In [28]:
# ==========================================
# Preprocessing
# ==========================================

train = preprocess(train)
test = preprocess(test)

print(train.shape)
print(test.shape)

(690088, 14)
(295753, 13)

In [29]:
# ==========================================
# Feature Engineering V2
# ==========================================

train = create_features(train)
test = create_features(test)

print(train.shape)
print(test.shape)

(690088, 34)
(295753, 33)

In [13]:
%whos

Variable                  Type         Data/Info
------------------------------------------------
CatBoostClassifier        type         <class 'catboost.core.CatBoostClassifier'>
StratifiedKFold           ABCMeta      <class 'sklearn.model_sel<...>._split.StratifiedKFold'>
TARGET                    str          health_condition
TEST_PATH                 str          ../data/test.csv
TRAIN_PATH                str          ../data/train.csv
X                         DataFrame    Shape: (690088, 14)
balanced_accuracy_score   function     <function balanced_accura<...>_score at 0x76d47a05dd00>
cat_feature_indices       list         n=6
categorical_features      list         n=6
np                        module       <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
objective                 function     <function objective at 0x76d4e8135ee0>
optuna                    module       <module 'optuna' from '/h<...>ages/optuna/__init__.py'>
pd                        module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
study                     Study        <optuna.study.study.Study<...>object at 0x76d47bd4bd10>
test                      DataFrame    Shape: (295753, 14)
test_ids                  Series       Shape: (295753,)
train                     DataFrame    Shape: (690088, 15)
train_ids                 Series       Shape: (690088,)
y                         Series       Shape: (690088,)

In [30]:
# ==========================================
# Prepare Features
# ==========================================

X = train.drop(columns=[TARGET]).copy()

y = train[TARGET].copy()

print("Features :", X.shape)

print("Target   :", y.shape)

Features : (690088, 33)
Target   : (690088,)

In [31]:
# ==========================================
# Detect Features
# ==========================================

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numerical_features = X.select_dtypes(
    include=[
        "int64",
        "float64",
        "int32",
        "float32"
    ]
).columns.tolist()

print("Categorical Features")

print(categorical_features)

print()

print("Numerical Features")

print(numerical_features)

Categorical Features
['diet_type', 'stress_level', 'sleep_quality', 'physical_activity_level', 'smoking_alcohol', 'gender', 'bmi_category', 'bmi_risk', 'stress_sleep', 'activity_diet', 'gender_activity', 'smoking_stress', 'diet_smoking']

Numerical Features
['sleep_duration', 'heart_rate', 'bmi', 'calorie_expenditure', 'step_count', 'exercise_duration', 'water_intake', 'activity_score', 'calories_per_step', 'water_per_exercise', 'exercise_sleep_ratio', 'steps_per_minute', 'calories_per_minute', 'activity_density', 'heart_activity', 'heart_steps', 'bmi_sleep', 'bmi_water', 'hydration_score', 'health_index']

In [32]:
# ==========================================
# Clean Missing Values
# ==========================================

for col in categorical_features:

    X[col] = (
        X[col]
        .fillna("Missing")
        .astype(str)
    )

for col in numerical_features:

    X[col] = X[col].fillna(
        X[col].median()
    )

print("Categorical Missing Values")

print(
    X[categorical_features]
    .isna()
    .sum()
    .sum()
)

print()

print("Numerical Missing Values")

print(
    X[numerical_features]
    .isna()
    .sum()
    .sum()
)

Categorical Missing Values
0

Numerical Missing Values
0

In [33]:
# ==========================================
# Final Check
# ==========================================

print("="*60)

print("Train Shape")

print(X.shape)

print()

print("Target Shape")

print(y.shape)

print()

print("Number of Features")

print(X.shape[1])

print()

print("Categorical Features")

print(len(categorical_features))

print()

print("Numerical Features")

print(len(numerical_features))

print("="*60)

============================================================
Train Shape
(690088, 33)

Target Shape
(690088,)

Number of Features
33

Categorical Features
13

Numerical Features
20
============================================================

In [34]:
# ==========================================
# Optuna Objective Function
# ==========================================

def objective(trial):

    bootstrap_type = trial.suggest_categorical(
        "bootstrap_type",
        ["Bayesian", "Bernoulli"]
    )

    params = {

        # GPU
        "task_type": "GPU",
        "devices": "0",

        # Objective
        "loss_function": "MultiClass",
        "eval_metric": "MultiClass",

        # Fixed
        "iterations": 1200,
        "random_seed": RANDOM_STATE,
        "verbose": False,
        "auto_class_weights": "Balanced",

        # Search Space
        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.10,
            log=True
        ),

        "depth": trial.suggest_int(
            "depth",
            5,
            10
        ),

        "l2_leaf_reg": trial.suggest_float(
            "l2_leaf_reg",
            1,
            15
        ),

        "random_strength": trial.suggest_float(
            "random_strength",
            0,
            5
        ),

        "border_count": trial.suggest_int(
            "border_count",
            64,
            255
        ),

        "grow_policy": trial.suggest_categorical(
            "grow_policy",
            ["SymmetricTree", "Depthwise"]
        ),

        "leaf_estimation_iterations": trial.suggest_int(
            "leaf_estimation_iterations",
            1,
            10
        ),

        "min_data_in_leaf": trial.suggest_int(
            "min_data_in_leaf",
            1,
            32
        ),

        "bootstrap_type": bootstrap_type
    }

    if bootstrap_type == "Bayesian":

        params["bagging_temperature"] = trial.suggest_float(
            "bagging_temperature",
            0,
            10
        )

    else:

        params["subsample"] = trial.suggest_float(
            "subsample",
            0.6,
            1.0
        )

    skf = StratifiedKFold(
        n_splits=3,
        shuffle=True,
        random_state=RANDOM_STATE
    )

    scores = []

    for train_idx, valid_idx in skf.split(X, y):

        X_train = X.iloc[train_idx].copy()
        X_valid = X.iloc[valid_idx].copy()

        y_train = y.iloc[train_idx]
        y_valid = y.iloc[valid_idx]

        model = CatBoostClassifier(**params)

        model.fit(
            X_train,
            y_train,
            eval_set=(X_valid, y_valid),
            cat_features=categorical_features,
            use_best_model=True,
            early_stopping_rounds=150
        )

        pred = model.predict(X_valid)

        score = balanced_accuracy_score(
            y_valid,
            pred
        )

        scores.append(score)

    return np.mean(scores)

In [35]:
# ==========================================
# Create Optuna Study
# ==========================================

study = optuna.create_study(

    direction="maximize",

    sampler=optuna.samplers.TPESampler(
        seed=RANDOM_STATE,
        multivariate=True
    ),

    pruner=optuna.pruners.MedianPruner(
        n_startup_trials=10
    )
)

print("Study Created Successfully")

[I 2026-07-29 19:42:17,761] A new study created in memory with name: no-name-28ca6f33-2ef6-4cdb-b9b2-09029cb20704

Study Created Successfully

In [36]:
study.optimize(
    objective,
    n_trials=1,
    show_progress_bar=True
)

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-29 19:43:53,812] Trial 0 finished with value: 0.9484940395215166 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05395030966670229, 'depth': 8, 'l2_leaf_reg': 3.1842609661941115, 'random_strength': 0.7799726016810132, 'border_count': 75, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 8, 'min_data_in_leaf': 1, 'subsample': 0.9879639408647978}. Best is trial 0 with value: 0.9484940395215166.

In [37]:
print(study.best_value)
print(study.best_params)

0.9484940395215166
{'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05395030966670229, 'depth': 8, 'l2_leaf_reg': 3.1842609661941115, 'random_strength': 0.7799726016810132, 'border_count': 75, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 8, 'min_data_in_leaf': 1, 'subsample': 0.9879639408647978}

In [38]:
# ==========================================
# Run Optuna Optimization
# ==========================================

N_TRIALS = 75

study.optimize(
    objective,
    n_trials=N_TRIALS,
    show_progress_bar=True
)

  0%|          | 0/75 [00:00<?, ?it/s]

[I 2026-07-29 19:47:08,475] Trial 1 finished with value: 0.9481123776788093 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.015199348301309814, 'depth': 6, 'l2_leaf_reg': 5.259391401433528, 'random_strength': 2.6237821581611893, 'border_count': 146, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 2, 'min_data_in_leaf': 10, 'bagging_temperature': 3.663618432936917}. Best is trial 0 with value: 0.9484940395215166.
[I 2026-07-29 19:51:02,011] Trial 2 finished with value: 0.948913816935996 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.015837031559118753, 'depth': 8, 'l2_leaf_reg': 9.293803964068594, 'random_strength': 0.23225206359998862, 'border_count': 180, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 31, 'subsample': 0.9233589392465844}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 19:53:57,924] Trial 3 finished with value: 0.9479959339142917 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04833180632488466, 'depth': 7, 'l2_leaf_reg': 2.7085352878269036, 'random_strength': 2.475884550556351, 'border_count': 70, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 10, 'bagging_temperature': 5.200680211778108}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 19:55:19,744] Trial 4 finished with value: 0.948419774232383 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09323621351781479, 'depth': 9, 'l2_leaf_reg': 14.152985181898648, 'random_strength': 4.474136752138244, 'border_count': 178, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 2, 'min_data_in_leaf': 2, 'bagging_temperature': 3.2533033076326436}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 19:57:00,977] Trial 5 finished with value: 0.9483814743588304 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0674120461070276, 'depth': 7, 'l2_leaf_reg': 4.933083135623331, 'random_strength': 2.7134804157912424, 'border_count': 91, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 25, 'bagging_temperature': 1.987156815341724}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 19:58:16,802] Trial 6 finished with value: 0.9488771378573349 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05091635945818555, 'depth': 9, 'l2_leaf_reg': 11.79778485360324, 'random_strength': 0.3702232586704518, 'border_count': 132, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 11, 'subsample': 0.6254233401144095}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 19:59:15,563] Trial 7 finished with value: 0.9488458223105072 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.053654503243520245, 'depth': 8, 'l2_leaf_reg': 13.420978396068572, 'random_strength': 2.3610746258097466, 'border_count': 86, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 6, 'min_data_in_leaf': 25, 'subsample': 0.7975182385457563}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 20:01:18,879] Trial 8 finished with value: 0.9455227173456336 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.010602764778958863, 'depth': 5, 'l2_leaf_reg': 1.4400085996142795, 'random_strength': 3.182052056318902, 'border_count': 124, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 3, 'min_data_in_leaf': 14, 'bagging_temperature': 7.555511385430487}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 20:03:07,888] Trial 9 finished with value: 0.9472024832066147 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.01948729021356848, 'depth': 5, 'l2_leaf_reg': 14.015767132796023, 'random_strength': 4.040601897822085, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 2, 'min_data_in_leaf': 29, 'bagging_temperature': 5.393422419156507}. Best is trial 2 with value: 0.948913816935996.
[I 2026-07-29 20:06:04,947] Trial 10 finished with value: 0.9489432469778644 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025785874153465407, 'depth': 7, 'l2_leaf_reg': 12.214875577511133, 'random_strength': 0.21728116595437116, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 31, 'subsample': 0.8676559573809419}. Best is trial 10 with value: 0.9489432469778644.
[I 2026-07-29 20:09:44,439] Trial 11 finished with value: 0.9487539304524789 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.019659230041287855, 'depth': 6, 'l2_leaf_reg': 12.473341375892046, 'random_strength': 0.08143048374240308, 'border_count': 98, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 8, 'min_data_in_leaf': 26, 'subsample': 0.8725367117849426}. Best is trial 10 with value: 0.9489432469778644.
[I 2026-07-29 20:12:20,129] Trial 12 finished with value: 0.9489971357651273 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027888447365825464, 'depth': 9, 'l2_leaf_reg': 11.878000078818477, 'random_strength': 1.1737350300508256, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 28, 'subsample': 0.889570414046958}. Best is trial 12 with value: 0.9489971357651273.
[I 2026-07-29 20:14:10,625] Trial 13 finished with value: 0.9488763697970439 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04970135057889077, 'depth': 7, 'l2_leaf_reg': 13.920818954481698, 'random_strength': 1.6523868591076443, 'border_count': 145, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 32, 'subsample': 0.7509977141542071}. Best is trial 12 with value: 0.9489971357651273.
[I 2026-07-29 20:16:20,175] Trial 14 finished with value: 0.9488827546370747 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.052626517757073825, 'depth': 10, 'l2_leaf_reg': 10.914309935450145, 'random_strength': 3.630077956735988, 'border_count': 169, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 23, 'subsample': 0.8581096499165712}. Best is trial 12 with value: 0.9489971357651273.
[I 2026-07-29 20:19:53,818] Trial 15 finished with value: 0.9488733555490064 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.013092732934678752, 'depth': 9, 'l2_leaf_reg': 13.736357764749643, 'random_strength': 2.460132270368905, 'border_count': 152, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 6, 'min_data_in_leaf': 29, 'subsample': 0.8836351306824903}. Best is trial 12 with value: 0.9489971357651273.
[I 2026-07-29 20:25:08,390] Trial 16 finished with value: 0.9469724802415099 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.039147814315130924, 'depth': 10, 'l2_leaf_reg': 14.287856559770404, 'random_strength': 0.15901000055408487, 'border_count': 173, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 8, 'min_data_in_leaf': 28, 'bagging_temperature': 9.533430150164182}. Best is trial 12 with value: 0.9489971357651273.
[I 2026-07-29 20:26:36,498] Trial 17 finished with value: 0.9491216832885455 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05653018257097331, 'depth': 7, 'l2_leaf_reg': 10.114743159702257, 'random_strength': 1.8394476575590861, 'border_count': 242, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 23, 'subsample': 0.7801327226455756}. Best is trial 17 with value: 0.9491216832885455.
[I 2026-07-29 20:27:49,973] Trial 18 finished with value: 0.9488886795036153 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07208855965823141, 'depth': 7, 'l2_leaf_reg': 13.273581095856779, 'random_strength': 1.2828555752116784, 'border_count': 245, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 6, 'min_data_in_leaf': 27, 'subsample': 0.7128736273411648}. Best is trial 17 with value: 0.9491216832885455.
[I 2026-07-29 20:29:24,721] Trial 19 finished with value: 0.9485880228280149 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029557878987445215, 'depth': 10, 'l2_leaf_reg': 13.608370167850177, 'random_strength': 1.6220758005492526, 'border_count': 197, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 28, 'subsample': 0.7677451480388974}. Best is trial 17 with value: 0.9491216832885455.
[I 2026-07-29 20:30:35,922] Trial 20 finished with value: 0.9491628550893854 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04674884910502585, 'depth': 6, 'l2_leaf_reg': 7.095899622743568, 'random_strength': 0.07447670853644439, 'border_count': 203, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 27, 'subsample': 0.7965812511573757}. Best is trial 20 with value: 0.9491628550893854.
[I 2026-07-29 20:31:27,089] Trial 21 finished with value: 0.9491643545493506 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07737742560138454, 'depth': 6, 'l2_leaf_reg': 5.037076244138847, 'random_strength': 0.08936643309671932, 'border_count': 216, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 5, 'min_data_in_leaf': 29, 'subsample': 0.7877560991663093}. Best is trial 21 with value: 0.9491643545493506.
[I 2026-07-29 20:32:27,864] Trial 22 finished with value: 0.949053377165949 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05140231723725761, 'depth': 6, 'l2_leaf_reg': 5.229761960840067, 'random_strength': 0.14997626570031292, 'border_count': 204, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 5, 'min_data_in_leaf': 32, 'subsample': 0.7626784774694623}. Best is trial 21 with value: 0.9491643545493506.
[I 2026-07-29 20:34:08,210] Trial 23 finished with value: 0.9492409124267872 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.040672576527795, 'depth': 6, 'l2_leaf_reg': 9.423681044803002, 'random_strength': 1.987317618283932, 'border_count': 223, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 24, 'subsample': 0.7790279450568134}. Best is trial 23 with value: 0.9492409124267872.
[I 2026-07-29 20:36:13,090] Trial 24 finished with value: 0.9491808506474667 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.042017789648319155, 'depth': 5, 'l2_leaf_reg': 9.798067098104674, 'random_strength': 2.4141943901012066, 'border_count': 213, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 8, 'min_data_in_leaf': 24, 'subsample': 0.6984483976721407}. Best is trial 23 with value: 0.9492409124267872.
[I 2026-07-29 20:37:51,183] Trial 25 finished with value: 0.9492915250797814 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031170121281856093, 'depth': 7, 'l2_leaf_reg': 12.28384702286287, 'random_strength': 3.4867694473261333, 'border_count': 250, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 27, 'subsample': 0.6762744002099903}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:40:37,326] Trial 26 finished with value: 0.9491565470915927 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04449384960190674, 'depth': 5, 'l2_leaf_reg': 13.509428325101224, 'random_strength': 3.1465054035027475, 'border_count': 183, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 22, 'subsample': 0.6594499136951272}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:42:07,971] Trial 27 finished with value: 0.9491061288508753 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.035590253997207486, 'depth': 8, 'l2_leaf_reg': 13.033556442309164, 'random_strength': 4.537849775892653, 'border_count': 254, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 25, 'subsample': 0.6643668568623937}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:43:29,504] Trial 28 finished with value: 0.949145444084158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05909175573773496, 'depth': 7, 'l2_leaf_reg': 6.900223269340637, 'random_strength': 2.1963104824126978, 'border_count': 193, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 29, 'subsample': 0.6785504679338329}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:44:42,148] Trial 29 finished with value: 0.949126616540427 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04605247354730332, 'depth': 6, 'l2_leaf_reg': 8.678224024357927, 'random_strength': 2.8891922899957776, 'border_count': 184, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 5, 'min_data_in_leaf': 14, 'subsample': 0.6096715046778778}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:46:49,932] Trial 30 finished with value: 0.9491279209869391 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03736344690001372, 'depth': 6, 'l2_leaf_reg': 9.638207720129802, 'random_strength': 2.8412931043504956, 'border_count': 240, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 23, 'bagging_temperature': 0.9646358492497917}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:48:51,136] Trial 31 finished with value: 0.9492312737137975 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021223280776924, 'depth': 6, 'l2_leaf_reg': 13.532674344613286, 'random_strength': 3.5696171804293555, 'border_count': 252, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 6, 'min_data_in_leaf': 28, 'bagging_temperature': 0.3162165534769201}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:50:42,269] Trial 32 finished with value: 0.9492329662272102 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.020576634265941966, 'depth': 7, 'l2_leaf_reg': 13.664474346436142, 'random_strength': 3.5641381603461646, 'border_count': 214, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 23, 'bagging_temperature': 0.39150568055354196}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:53:25,773] Trial 33 finished with value: 0.9491481533589394 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.013293139026487072, 'depth': 6, 'l2_leaf_reg': 11.476310992390877, 'random_strength': 3.3257849595200115, 'border_count': 224, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 6, 'min_data_in_leaf': 32, 'bagging_temperature': 0.013034165348403237}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:55:44,144] Trial 34 finished with value: 0.9492058152658526 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.011582743199692654, 'depth': 7, 'l2_leaf_reg': 12.640213764358288, 'random_strength': 3.9853135391220644, 'border_count': 180, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 4, 'min_data_in_leaf': 16, 'bagging_temperature': 0.4633745546374256}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 20:59:04,569] Trial 35 finished with value: 0.9491530851312066 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.015052341396158186, 'depth': 5, 'l2_leaf_reg': 12.719740241704585, 'random_strength': 3.864735441494442, 'border_count': 231, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 23, 'subsample': 0.6032830487214761}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 21:01:57,316] Trial 36 finished with value: 0.9490696442554195 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02446852951369775, 'depth': 5, 'l2_leaf_reg': 12.110405354282786, 'random_strength': 4.306711875890705, 'border_count': 251, 'grow_policy': 'SymmetricTree', 'leaf_estimation_iterations': 7, 'min_data_in_leaf': 29, 'bagging_temperature': 0.27808208118279243}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 21:04:18,949] Trial 37 finished with value: 0.9488299722808405 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03188701223754095, 'depth': 7, 'l2_leaf_reg': 12.592903711993246, 'random_strength': 3.2073574550682866, 'border_count': 209, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 5, 'min_data_in_leaf': 22, 'bagging_temperature': 2.3964510829282997}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 21:06:15,555] Trial 38 finished with value: 0.949185671137656 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.017740057159078483, 'depth': 7, 'l2_leaf_reg': 13.510331610844052, 'random_strength': 2.217502365093191, 'border_count': 194, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 24, 'bagging_temperature': 0.11668004280609845}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 21:09:36,125] Trial 39 finished with value: 0.9486096282944936 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02518758118153654, 'depth': 5, 'l2_leaf_reg': 14.69596540975196, 'random_strength': 3.871515344494471, 'border_count': 224, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 23, 'bagging_temperature': 2.7168090472022466}. Best is trial 25 with value: 0.9492915250797814.
[I 2026-07-29 21:11:18,058] Trial 40 finished with value: 0.9492965885036817 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026821643970370485, 'depth': 7, 'l2_leaf_reg': 9.635014597314086, 'random_strength': 3.8653013418352993, 'border_count': 243, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 30, 'subsample': 0.7088809033783928}. Best is trial 40 with value: 0.9492965885036817.
[I 2026-07-29 21:12:41,242] Trial 41 finished with value: 0.9492591998333381 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03464899207242917, 'depth': 7, 'l2_leaf_reg': 7.490792841190333, 'random_strength': 4.718560745961408, 'border_count': 215, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 25, 'subsample': 0.7260848819897291}. Best is trial 40 with value: 0.9492965885036817.
[I 2026-07-29 21:14:07,122] Trial 42 finished with value: 0.9490141094109189 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03676129720560533, 'depth': 8, 'l2_leaf_reg': 4.050255431286706, 'random_strength': 4.204430282042311, 'border_count': 189, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 21, 'subsample': 0.7192980757458413}. Best is trial 40 with value: 0.9492965885036817.
[I 2026-07-29 21:15:59,049] Trial 43 finished with value: 0.9490900901748671 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02252301506743446, 'depth': 7, 'l2_leaf_reg': 10.826489605582331, 'random_strength': 3.0703560165348973, 'border_count': 197, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 31, 'subsample': 0.7176296029342595}. Best is trial 40 with value: 0.9492965885036817.
[I 2026-07-29 21:17:44,579] Trial 44 finished with value: 0.9491237767812493 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032646678391227035, 'depth': 6, 'l2_leaf_reg': 7.160514005298548, 'random_strength': 4.870524086049421, 'border_count': 227, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 23, 'subsample': 0.7062972020367302}. Best is trial 40 with value: 0.9492965885036817.
[I 2026-07-29 21:20:40,918] Trial 45 finished with value: 0.9474343860325932 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04947349472864818, 'depth': 8, 'l2_leaf_reg': 14.77610382334642, 'random_strength': 4.4763427534233236, 'border_count': 229, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 10, 'min_data_in_leaf': 31, 'bagging_temperature': 6.92264929188905}. Best is trial 40 with value: 0.9492965885036817.

In [44]:
print(study.best_value)
print(study.best_params)

0.9493068522610774
{'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03309416821002669, 'depth': 7, 'l2_leaf_reg': 10.801507310686478, 'random_strength': 0.898531201248234, 'border_count': 253, 'grow_policy': 'Depthwise', 'leaf_estimation_iterations': 9, 'min_data_in_leaf': 25, 'subsample': 0.6828948177465322}

In [39]:
# ==========================================
# Best Trial
# ==========================================

print("=" * 60)

print("Best CV Score")
print(study.best_value)

print()

print("Best Parameters")

for key, value in study.best_params.items():
    print(f"{key}: {value}")

print("=" * 60)

============================================================
Best CV Score
0.9493068522610774

Best Parameters
bootstrap_type: Bernoulli
learning_rate: 0.03309416821002669
depth: 7
l2_leaf_reg: 10.801507310686478
random_strength: 0.898531201248234
border_count: 253
grow_policy: Depthwise
leaf_estimation_iterations: 9
min_data_in_leaf: 25
subsample: 0.6828948177465322
============================================================

In [45]:
# ==========================================
# Save Best Parameters
# ==========================================

best_params = study.best_params.copy()

best_params.update({

    "iterations": 1200,
    "loss_function": "MultiClass",
    "eval_metric": "MultiClass",

    "task_type": "GPU",
    "devices": "0",

    "random_seed": RANDOM_STATE,
    "verbose": 200,

    "auto_class_weights": "Balanced"

})

with open("../output/models/best_params.json", "w") as f:
    json.dump(best_params, f, indent=4)

print("Saved: models/best_params.json")

Saved: models/best_params.json

In [41]:
# Optimization History
import optuna.visualization as vis

vis.plot_optimization_history(study)

In [42]:
# Parameter Importance
vis.plot_param_importances(study)

In [43]:
# Parallel Coordinate Plot
vis.plot_parallel_coordinate(study)

[W 2026-07-29 22:30:37,926] Your study has only completed trials with missing parameters.

In [46]:
# ==========================================
# Best Parameters from Optuna
# ==========================================

best_params = {
    "bootstrap_type": "Bernoulli",
    "learning_rate": 0.03309416821002669,
    "depth": 7,
    "l2_leaf_reg": 10.801507310686478,
    "random_strength": 0.898531201248234,
    "border_count": 253,
    "grow_policy": "Depthwise",
    "leaf_estimation_iterations": 9,
    "min_data_in_leaf": 25,
    "subsample": 0.6828948177465322,

    # Fixed Parameters
    "iterations": 1200,
    "loss_function": "MultiClass",
    "eval_metric": "MultiClass",

    "task_type": "GPU",
    "devices": "0",

    "auto_class_weights": "Balanced",
    "random_seed": RANDOM_STATE,
    "verbose": False
}

In [47]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

scores = []

for fold, (train_idx, valid_idx) in enumerate(skf.split(X, y), 1):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = CatBoostClassifier(**best_params)

    model.fit(
        X_train,
        y_train,
        cat_features=categorical_features,
        eval_set=(X_valid, y_valid),
        use_best_model=True,
        early_stopping_rounds=150
    )

    pred = model.predict(X_valid)

    score = balanced_accuracy_score(y_valid, pred)

    scores.append(score)

    print(f"Fold {fold}: {score:.6f}")

print("\nMean CV:", np.mean(scores))
print("Std CV :", np.std(scores))

Fold 1: 0.949997
Fold 2: 0.951262
Fold 3: 0.948970
Fold 4: 0.949322
Fold 5: 0.947685

Mean CV: 0.9494470167050434
Std CV : 0.0011783808015736609

In [48]:
# Train Final Model
final_model = CatBoostClassifier(**best_params)

final_model.fit(
    X,
    y,
    cat_features=categorical_features
)

CatBoostClassifier(auto_class_weights='Balanced', bootstrap_type='Bernoulli', border_count=253, depth=7, devices='0', eval_metric='MultiClass', grow_policy='Depthwise', iterations=1200, l2_leaf_reg=10.801507310686478, leaf_estimation_iterations=9, learning_rate=0.03309416821002669, loss_function='MultiClass', min_data_in_leaf=25, random_seed=42, random_strength=0.898531201248234, subsample=0.6828948177465322, task_type='GPU', verbose=False)

In [64]:
# Save Model

os.makedirs("models", exist_ok=True)

final_model.save_model("../output/models/shrp_catboost_pro_v1_0.94985.cbm")

print("Model save.")

Model save.

In [52]:
feature_importance = pd.DataFrame({

    "Feature": X.columns,
    "Importance": final_model.get_feature_importance()

})

feature_importance = feature_importance.sort_values(
    "Importance",
    ascending=False
)

feature_importance.head(50)

                    Feature  Importance
0            sleep_duration   42.909324
8              stress_level   22.579465
2                       bmi   15.338961
10  physical_activity_level    7.986294
28             stress_sleep    1.560838
30          gender_activity    1.308785
31           smoking_stress    1.006550
22                bmi_sleep    0.782306
11          smoking_alcohol    0.562747
6              water_intake    0.525334
1                heart_rate    0.496588
29            activity_diet    0.377898
3       calorie_expenditure    0.368612
13           activity_score    0.338785
14        calories_per_step    0.302816
18      calories_per_minute    0.294801
17         steps_per_minute    0.292139
24          hydration_score    0.289275
23                bmi_water    0.283396
21              heart_steps    0.280165
16     exercise_sleep_ratio    0.276276
4                step_count    0.265456
15       water_per_exercise    0.258889
20           heart_activity    0.239530
25             health_index    0.206190
9             sleep_quality    0.197164
32             diet_smoking    0.189494
5         exercise_duration    0.165229
26             bmi_category    0.097551
19         activity_density    0.080221
12                   gender    0.062702
7                 diet_type    0.059651
27                 bmi_risk    0.016567

In [53]:
# save the Feature 
feature_importance.to_csv(
    "../output/models/feature_importance.csv",
    index=False
)

In [57]:
print(test.columns)
print(test_processed.columns)

Index(['sleep_duration', 'heart_rate', 'bmi', 'calorie_expenditure',
       'step_count', 'exercise_duration', 'water_intake', 'diet_type',
       'stress_level', 'sleep_quality', 'physical_activity_level',
       'smoking_alcohol', 'gender', 'activity_score', 'calories_per_step',
       'water_per_exercise', 'exercise_sleep_ratio', 'steps_per_minute',
       'calories_per_minute', 'activity_density', 'heart_activity',
       'heart_steps', 'bmi_sleep', 'bmi_water', 'hydration_score',
       'health_index', 'bmi_category', 'bmi_risk', 'stress_sleep',
       'activity_diet', 'gender_activity', 'smoking_stress', 'diet_smoking'],
      dtype='str')
Index(['sleep_duration', 'heart_rate', 'bmi', 'calorie_expenditure',
       'step_count', 'exercise_duration', 'water_intake', 'diet_type',
       'stress_level', 'sleep_quality', 'physical_activity_level',
       'smoking_alcohol', 'gender', 'activity_score', 'calories_per_step',
       'water_per_exercise', 'exercise_sleep_ratio', 'steps_per_minute',
       'calories_per_minute', 'activity_density', 'heart_activity',
       'heart_steps', 'bmi_sleep', 'bmi_water', 'hydration_score',
       'health_index', 'bmi_category', 'bmi_risk', 'stress_sleep',
       'activity_diet', 'gender_activity', 'smoking_stress', 'diet_smoking'],
      dtype='str')

In [58]:
print(test.head())
print(test.shape)

   sleep_duration  heart_rate    bmi  calorie_expenditure  step_count  \
0            5.35        64.9  23.48               2745.0     14167.0
1            6.99        83.1  22.42               1773.0      6801.0
2            6.68        59.7  24.14               3040.0     13250.0
3            7.13        78.5  26.26               2494.0      6331.0
4            5.49        77.7  23.29               1828.0     13894.0

   exercise_duration  water_intake diet_type stress_level sleep_quality  ...  \
0               59.5          1.86       veg         high          poor  ...
1               24.5          2.40  balanced         high          poor  ...
2               48.5          2.76  balanced       medium          poor  ...
3               56.9          2.34       veg          low          good  ...
4               39.4          2.45       veg         high       average  ...

  bmi_water hydration_score health_index  bmi_category  bmi_risk  \
0   43.6728        0.000677        66.71        normal    normal
1   53.8080        0.001353        33.89        normal    normal
2   66.6264        0.000908        57.94        normal    normal
3   61.4484        0.000938        66.37    overweight      over
4   57.0605        0.001340        47.34        normal    normal

   stress_sleep       activity_diet  gender_activity   smoking_stress  \
0     high_poor          active_veg      male_active  occasional_high
1     high_poor  sedentary_balanced  other_sedentary         yes_high
2   medium_poor     active_balanced   Unknown_active        no_medium
3      low_good        moderate_veg   other_moderate          yes_low
4  high_average          active_veg     other_active  occasional_high

     diet_smoking
0  veg_occasional
1    balanced_yes
2     balanced_no
3         veg_yes
4  veg_occasional

[5 rows x 33 columns]
(295753, 33)

In [60]:
# ==========================================
# Preprocess Test Data
# ==========================================

# test_ids was already saved earlier:
# test_ids = test["id"].copy()

test_processed = preprocess(test.copy())
test_processed = create_features(test_processed)

X_test = test_processed.copy()

# Drop id only if it still exists
if "id" in X_test.columns:
    X_test = X_test.drop(columns=["id"])

# Ensure same feature order as training
X_test = X_test[X.columns]

In [65]:
predictions = final_model.predict(X_test).ravel()

submission = pd.DataFrame({
    "id": test_ids,
    "health_condition": predictions
})

submission.to_csv("../output/submissions/submission_shrp_catboost_pro_0.94985.csv", index=False)

submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy